# Generated by Django 4.2.13 on 2024-05-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_student_courses_student_years'),
        ('course', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='attended',
            field=models.ManyToManyField(blank=True, null=True, related_name='attended', to='useraccount.student'),
        ),
    ]
