# Generated by Django 4.2.13 on 2024-05-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_student_courses'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
            ],
        ),
    ]
